---
- name: Change root password for all hosts
  hosts: all
  become: yes
  gather_facts: no

  vars_prompt:
    - name: "root_password"
      prompt: "Enter the new root password"
      private: yes

  tasks:
    - name: Change root password
      user:
        name: root
        password: "{{ root_password | password_hash('sha512') }}"

